### ISSUE TITLE
调整markdown字体颜色

### ISSUE THREAD

**Issue by piggyzss** [shixiaohu2206/hexo-theme-huhu#1]
你好，非常喜欢你的主题，向请教您怎样设置markdown文档的字体和颜色呢，多谢～

**Comment by shixiaohu2206** [comment]
hi，你好，感谢你 的喜欢～

可以自己fork一份，自己修改一下吧，markdown的css，目前是耦合在一起的，后面有时候，我会把markdown的css独立成模块，可以修改
