### ISSUE TITLE
hljs

### ISSUE THREAD

**Issue by LuckyFBB** [shixiaohu2206/hexo-theme-huhu#16]
为什么我这个默认的code下面没有hljs这个类。
clone之后没有做任何修改

**Comment by shixiaohu2206** [comment]
需要这个hljs类，做什么用？

**Comment by Wakie01** [comment]
你好，请问highlight出现这种情况该怎么解决呢？
![1](https://user-images.githubusercontent.com/33743772/90974134-e29d5300-e55a-11ea-8a3b-3f703f7e1270.png)

**Comment by shixiaohu2206** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
