### ISSUE TITLE
为什么我应用了您的主题和你的博客差好多？

### ISSUE THREAD

**Issue by caozhi6789** [shixiaohu2206/hexo-theme-huhu#4]
侧边栏在左边，你的博客是在右边。网页显示也很怪，完全不同。

**Comment by shixiaohu2206** [comment]
不好意思，我最近还在修改主题，目前还在完善中

**Comment by shixiaohu2206** [comment]
> 侧边栏在左边，你的博客是在右边。网页显示也很怪，完全不同。

不好意思，我最近还在修改主题，目前还在完善中

**Comment by shixiaohu2206** [comment]
> 侧边栏在左边，你的博客是在右边。网页显示也很怪，完全不同。



嗨，你好，我昨天更新了README.md使用文档，并且在Hexo官方的测试Demo中完整的测试一遍，按照README.md安装，应该就可以正常使用了

如果还不能解决问题，请留言，感谢~
