### ISSUE TITLE
无法正常显示

### ISSUE THREAD

**Issue by yusaiwen** [shixiaohu2206/hexo-theme-huhu#8]
开放者您好~
无意间发现您更新了theme，见到您设计的新theme美观了不少就好像看到一个长大了的孩子，欣喜不已。
今日欲换成您新的theme，奈何我把theme换成huhu后网页加载不出来，更新了npm也无果，笔者不是程序员不太能读懂代码，但懂得报错，于是将error放在下面供您参考.
ERROR Script load failed: themes\huhu\scripts\index.js
Error: Cannot find module 'shelljs/global'
 一开始显著没有无法加载webpack，予以更新后仍报错并不能显示出任何内容.
以上
谢谢您的作品，以及如果我有打扰到您我表示很抱歉。

此致

**Comment by shixiaohu2206** [comment]
哈哈，’一个长大了的孩子‘，这个形容词来很新颖！

首先感谢您的回复，这个报错是没有安装shelljs这个包
请安装以下这个包
执行以下命令 npm i --save shelljs

最近服务器要到期了，暂时在忙搬迁新服务器。等后面有空了，会重构一下代码，并且写一个使用文档。

如果安装shelljs包后，还不能解决问题，请在以下留言，我会及时协助你！

**Comment by shixiaohu2206** [comment]
> 开放者您好~
> 无意间发现您更新了theme，见到您设计的新theme美观了不少就好像看到一个长大了的孩子，欣喜不已。
> 今日欲换成您新的theme，奈何我把theme换成huhu后网页加载不出来，更新了npm也无果，笔者不是程序员不太能读懂代码，但懂得报错，于是将error放在下面供您参考.
> ERROR Script load failed: themes\huhu\scripts\index.js
> Error: Cannot find module 'shelljs/global'
> 一开始显著没有无法加载webpack，予以更新后仍报错并不能显示出任何内容.
> 以上
> 谢谢您的作品，以及如果我有打扰到您我表示很抱歉。
> 
> 此致

嗨，你好，我昨天更新了README.md使用文档，并且在Hexo官方的测试Demo中完整的测试一遍，按照README.md安装，应该就可以正常使用了

如果还不能解决问题，请留言，感谢~

**Comment by 1eng** [comment]
开发者你好!我很高兴使用你写的博客模板,请问文章浏览统计怎么设置,就是文章顶端的那个眼睛旁边会显示浏览次数,我是没有任何显示呀.如果你看到这个issue的话,能否解答下?
